Data prepocessing
DimaZapolsky/Yandex_Sirius_audio_visual_correspondence pull request #2
Opened 2019-11-05 12:24 UTC by DimaZapolsky

2019-11-05 12:34 UTC, nickkartashev requested changes

2019-11-05 12:34 UTC, nickkartashev commented on data_preprocessing/create_dataset.py
> +        data = data[2]
А тут есть "We further re-sample this signal on a log-frequency scale to obtain a 256 × 256 T-F"?

2019-11-05 12:35 UTC, DimaZapolsky commented on data_preprocessing/create_dataset.py
> +        data = data[2]
> А тут есть "We further re-sample this signal on a log-frequency scale to obtain a 256 × 256 T-F"?

No :(

2019-11-06 15:41 UTC, nickkartashev approved these changes
Good job!

2019-11-06 15:41 UTC, merged